CREATE TABLE
    ZARTICLE (
        Z_PK INTEGER PRIMARY KEY,
        Z_ENT INTEGER,
        Z_OPT INTEGER,
        ZRAWINDEX INTEGER,
        ZRAWISUNREAD INTEGER,
        Z2RAWARTICLES INTEGER
    );

CREATE TABLE
    ZBOOK (
        Z_PK INTEGER PRIMARY KEY,
        Z_ENT INTEGER,
        Z_OPT INTEGER,
        ZISHIDDENBYUSER INTEGER,
        ZRAWAUTOSHELVE INTEGER,
        ZRAWBOOKSTATE INTEGER,
        ZRAWBOOKTYPE INTEGER,
        ZRAWBOOKUPGRADESNEEDED INTEGER,
        ZRAWCURRENTPOSITION INTEGER,
        ZRAWERL INTEGER,
        ZRAWFILESIZE INTEGER,
        ZRAWHASCOMPANION INTEGER,
        ZRAWHASFIXEDMOPHIGHLIGHTS INTEGER,
        ZRAWINBOOKCOVERCHECKED INTEGER,
        ZRAWISARCHIVABLE INTEGER,
        ZRAWISDICTIONARY INTEGER,
        ZRAWISENCRYPTED INTEGER,
        ZRAWISHIDDEN INTEGER,
        ZRAWISKEPT INTEGER,
        ZRAWISMULTIMEDIA INTEGER,
        ZRAWISPENDINGVERIFICATION INTEGER,
        ZRAWISSMDCREATEDDICTIONARY INTEGER,
        ZRAWISTRANSLATIONDICTIONARY INTEGER,
        ZRAWISUNREAD INTEGER,
        ZRAWLASTACCESSTIME INTEGER,
        ZRAWLASTOPENSUCCEEDED INTEGER,
        ZRAWLASTVIEW INTEGER,
        ZRAWMAXLOCATION INTEGER,
        ZRAWMAXPOSITION INTEGER,
        ZRAWNCXINFOSTORED INTEGER,
        ZRAWPROGRESSDOTCATEGORY INTEGER,
        ZRAWPUBLICATIONDATE INTEGER,
        ZRAWREADSTATE INTEGER,
        ZRAWREADSTATEORIGIN INTEGER,
        ZRAWREADINGMODE INTEGER,
        ZRAWUSERVISIBLELABELING INTEGER,
        ZCOMPANION INTEGER,
        ZALTERNATESORTTITLE VARCHAR,
        ZBOOKID VARCHAR,                    -- Amazon の商品番号?
        ZBUNDLEPATH VARCHAR,
        ZCONTENTTAGS VARCHAR,               -- ;MANGA とか ";" で区切る?
        ZDICTIONARYLOCALEID VARCHAR,        -- 辞書の言語。locale 式(ex. en_US)
        ZDICTIONARYSHORTTITLE VARCHAR,      -- 辞書種別? (ex. "French - English")
        ZDICTIONARYSOURCELANG VARCHAR,      -- 辞書のソース言語
        ZDISPLAYTITLE VARCHAR,              -- 書名
        ZGROUPID VARCHAR,                   -- ??
        ZLANGUAGE VARCHAR,                  -- 言語 (Unknown が多い?)
        ZLONGCURRENTPOSITION VARCHAR,       -- 今、どこまで読んでいるか(長い版)
        ZLONGMAXPOSITION VARCHAR,           -- 最長でどこまで読んでいるか
        ZMIMETYPE VARCHAR,                  -- application/x-mobipocket-ebook とか
        ZPARENTASIN VARCHAR,                -- ?? Parent ASIN?
        ZPATH VARCHAR,                      -- ファイルの場所?
        ZPERASINGUID VARCHAR,               -- ??
        ZRAWPUBLISHER VARCHAR,              -- 出版社
        ZSHELF VARCHAR,                     -- ??
        ZSORTTITLE VARCHAR,                 -- ソート用の書名(カタカナ)とか
        ZWATERMARK VARCHAR,                 -- ??
        ZALTERNATESORTAUTHOR BLOB,
        ZAUTHOR BLOB,
        ZEXTENDEDMETADATA BLOB,
        ZORIGINS BLOB,
        ZSORTAUTHOR BLOB,
        ZSYNCMETADATAATTRIBUTES BLOB,
        ZRAWTITLEDETAILSJSON BLOB
    );

CREATE TABLE
    ZBOOKEXT (
        Z_PK INTEGER PRIMARY KEY,
        Z_ENT INTEGER,
        Z_OPT INTEGER,
        ZBOOKID VARCHAR,
        ZDOWNLOADORIGIN VARCHAR
    );

CREATE TABLE
    ZBOOKUPDATE (
        Z_PK INTEGER PRIMARY KEY,
        Z_ENT INTEGER,
        Z_OPT INTEGER,
        ZPLUGINRETRIES INTEGER,
        ZRAWUPDATESTATE INTEGER,
        ZENDTIME TIMESTAMP,
        ZLASTUPDATEATTEMPT TIMESTAMP,
        ZSTARTTIME TIMESTAMP,
        ZBOOKID VARCHAR,
        ZUPDATEID VARCHAR,
        ZUPDATEREQUESTID VARCHAR
    );

CREATE TABLE
    ZCOLLECTIONITEM (
        Z_PK INTEGER PRIMARY KEY,
        Z_ENT INTEGER,
        Z_OPT INTEGER,
        ZSYNCHINT INTEGER,
        ZBOOK INTEGER,
        ZCOLLECTION INTEGER,
        ZRAWORDER FLOAT,
        ZCOLLECTIONID VARCHAR,
        ZITEMID VARCHAR
    );

CREATE TABLE
    ZCOLLECTIONV2 (
        Z_PK INTEGER PRIMARY KEY,
        Z_ENT INTEGER,
        Z_OPT INTEGER,
        ZRAWLASTACCESSTIME INTEGER,
        ZSYNCHINT INTEGER,
        ZALTERNATESORTNAME VARCHAR,
        ZCOLLECTIONID VARCHAR,
        ZCONTENTTYPE VARCHAR,
        ZLANGUAGE VARCHAR,
        ZNAME VARCHAR,
        ZPHONETICNAME VARCHAR,
        ZSORTNAME VARCHAR
    );

CREATE TABLE
    ZGROUP (
        Z_PK INTEGER PRIMARY KEY,
        Z_ENT INTEGER,
        Z_OPT INTEGER,
        ZLASTACCESSTIME INTEGER,
        ZLASTACCESSTIMEFORDOWNLOAD INTEGER,
        ZRAWPUBLICATIONDATE INTEGER,
        ZTOTALSIZE INTEGER,
        ZSERIESCOVERIMAGE INTEGER,
        ZGROUPID VARCHAR,
        ZALTERNATESORTAUTHOR VARCHAR,
        ZALTERNATESORTTITLE VARCHAR,
        ZCOLLECTIONORDERTYPE VARCHAR,
        ZCOVERBOOKID VARCHAR,
        ZDETAILPAGEASIN VARCHAR,
        ZDISPLAYAUTHOR VARCHAR,
        ZDISPLAYNAME VARCHAR,
        ZSERIESTYPE VARCHAR,
        ZSORTAUTHOR VARCHAR,
        ZSORTTITLE VARCHAR,
        ZRAWSERIESCOLLECTIONTYPES BLOB
    );

CREATE TABLE
    ZGROUPITEM (
        Z_PK INTEGER PRIMARY KEY,
        Z_ENT INTEGER,
        Z_OPT INTEGER,
        ZBOOK INTEGER,
        ZPARENTCONTAINER INTEGER,
        Z7_PARENTCONTAINER INTEGER,
        ZPOSITION INTEGER,
        ZITEMID VARCHAR,
        ZPOSITIONLABEL VARCHAR,
        ZRAWITEMCOLLECTIONTYPE VARCHAR
    );

CREATE TABLE
    ZSERIESAUTHOR (
        Z_PK INTEGER PRIMARY KEY,
        Z_ENT INTEGER,
        Z_OPT INTEGER,
        ZSERIES INTEGER,
        Z_FOK_SERIES INTEGER,
        ZAUTHORNAME VARCHAR,
        ZAUTHORPRONUNCIATION VARCHAR
    );

CREATE TABLE
    ZSERIESIMAGE (
        Z_PK INTEGER PRIMARY KEY,
        Z_ENT INTEGER,
        Z_OPT INTEGER,
        ZSERIES INTEGER,
        ZEXTENSION VARCHAR,
        ZIMAGEID VARCHAR
    );

CREATE INDEX ZARTICLE_Z2RAWARTICLES_INDEX ON ZARTICLE (Z2RAWARTICLES);

CREATE INDEX ZBOOK_ZCOMPANION_INDEX ON ZBOOK (ZCOMPANION);

CREATE INDEX Z_Book_byBookIdIndex ON ZBOOK (ZBOOKID COLLATE BINARY ASC);

CREATE INDEX Z_Book_byPathIndex ON ZBOOK (ZPATH COLLATE BINARY ASC);

CREATE INDEX Z_Book_byRawBookStateIndex ON ZBOOK (ZRAWBOOKSTATE COLLATE BINARY ASC);

CREATE INDEX Z_Book_byRawBookTypeIndex ON ZBOOK (ZRAWBOOKTYPE COLLATE BINARY ASC);

CREATE INDEX Z_Book_byRawIsArchivableIndex ON ZBOOK (ZRAWISARCHIVABLE COLLATE BINARY ASC);

CREATE INDEX Z_Book_byRawIsEncryptedIndex ON ZBOOK (ZRAWISENCRYPTED COLLATE BINARY ASC);

CREATE INDEX Z_Book_byRawLastAccessTimeIndex ON ZBOOK (ZRAWLASTACCESSTIME COLLATE BINARY ASC);

CREATE INDEX Z_BookExt_byBookIdIndex ON ZBOOKEXT (ZBOOKID COLLATE BINARY ASC);

CREATE INDEX Z_BookUpdate_byBookIdIndex ON ZBOOKUPDATE (ZBOOKID COLLATE BINARY ASC);

CREATE INDEX Z_BookUpdate_byRawUpdateStateIndex ON ZBOOKUPDATE (ZRAWUPDATESTATE COLLATE BINARY ASC);

CREATE INDEX Z_BookUpdate_byUpdateRequestIdIndex ON ZBOOKUPDATE (ZUPDATEREQUESTID COLLATE BINARY ASC);

CREATE INDEX ZCOLLECTIONITEM_ZBOOK_INDEX ON ZCOLLECTIONITEM (ZBOOK);

CREATE INDEX ZCOLLECTIONITEM_ZCOLLECTION_INDEX ON ZCOLLECTIONITEM (ZCOLLECTION);

CREATE INDEX Z_CollectionItem_byCollectionIdIndex ON ZCOLLECTIONITEM (ZCOLLECTIONID COLLATE BINARY ASC);

CREATE INDEX Z_CollectionItem_byItemIdIndex ON ZCOLLECTIONITEM (ZITEMID COLLATE BINARY ASC);

CREATE INDEX Z_CollectionV2_byCollectionIdIndex ON ZCOLLECTIONV2 (ZCOLLECTIONID COLLATE BINARY ASC);

CREATE INDEX ZGROUP_ZSERIESCOVERIMAGE_INDEX ON ZGROUP (ZSERIESCOVERIMAGE);

CREATE INDEX ZGROUP_Z_ENT_INDEX ON ZGROUP (Z_ENT);

CREATE INDEX Z_Group_byGroupIdIndex ON ZGROUP (ZGROUPID COLLATE BINARY ASC);

CREATE INDEX ZGROUPITEM_ZBOOK_INDEX ON ZGROUPITEM (ZBOOK);

CREATE INDEX ZGROUPITEM_ZPARENTCONTAINER_INDEX ON ZGROUPITEM (ZPARENTCONTAINER);

CREATE INDEX ZGROUPITEM_Z_ENT_INDEX ON ZGROUPITEM (Z_ENT);

CREATE INDEX Z_GroupItem_byItemIdIndex ON ZGROUPITEM (ZITEMID COLLATE BINARY ASC);

CREATE INDEX ZSERIESAUTHOR_ZSERIES_INDEX ON ZSERIESAUTHOR (ZSERIES);

CREATE INDEX ZSERIESIMAGE_ZSERIES_INDEX ON ZSERIESIMAGE (ZSERIES);

CREATE TABLE
    Z_PRIMARYKEY (
        Z_ENT INTEGER PRIMARY KEY,
        Z_NAME VARCHAR,
        Z_SUPER INTEGER,
        Z_MAX INTEGER
    );

CREATE TABLE
    Z_METADATA (
        Z_VERSION INTEGER PRIMARY KEY,
        Z_UUID VARCHAR(255),
        Z_PLIST BLOB
    );

CREATE TABLE
    Z_MODELCACHE (Z_CONTENT BLOB);

/* No STAT tables available */